server:
  port: ${SERVER_PORT:8002}

info:
  app:
    name: inventory-service
    description: Servicio de Administracion de inventario
    version: 1.0.0
  java-vendor: ${java.specification.vendor}

spring:
  application:
    name: inventoryservice
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_inventory
    username: ecommerce_user
    password: ecommerce_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  messages:
    basename: ValidationMessages
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:
          orderConfirmedEvent:com.dzerain.inventoryservice.kafka.event.OrderConfirmedEvent,
          orderCancelledEvent:com.dzerain.inventoryservice.kafka.event.OrderCancelledEvent
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping:
          orderPlacedEvent:com.dzerain.inventoryservice.kafka.event.OrderPlacedEvent
        spring.json.trusted.packages: "*"

logging:
  level:
    org.hibernate.SQL: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html