server:
  port: ${SERVER_PORT:8000}

info:
  app:
    name: product-service
    description: Servicio de Administracion de productos
    version: 1.0.0
  java-vendor: ${java.specification.vendor}

spring:
  application:
    name: product-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_products
    username: ecommerce_user
    password: ecommerce_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  messages:
    basename: ValidationMessages
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: productCreatedEvent:com.dzerain.product.kafka.event.ProductCreatedEvent
        spring.json.trusted.packages: "*"


logging:
  level:
    org.hibernate.SQL: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html