server:
  port: ${SERVER_PORT:8000}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_products
    username: ecommerce_user
    password: ecommerce_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  messages:
    basename: ValidationMessages
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: productCreatedEvent:com.dzerain.product.kafka.event.ProductCreatedEvent
        spring.json.trusted.packages: "*"

logging:
  level:
    org.hibernate.SQL: INFO